import { Lesson, Challenge } from "../types";

export const LESSONS: Lesson[] = [
  {
    id: "intro",
    section: "1. Core Logic",
    title: "Introduction to AI Automations",
    contentMarkdown: `### 🚀 What is an AI-Augmented Automation?

Traditional automation (like classic Zapier, IFTTT, or basic cron jobs) relies on **strict, literal mappings**: 
- *If a new email is received, save the sender's email to a Spreadsheet.* 

This works for static structures, but breaks down the moment the data is unstructured (like standard conversational text, custom voice transcripts, or free-form feedback).

**Enter AI Automations.** By inserting cognitive steps (Large Language Models) inside your pipelines, you can now process high-complexity, unstructured data in the background:
- 💡 **Extract details:** Read invoice PDFs or customer requests and extract names, costs, or due dates.
- 💡 **Sentiment classification:** Score customer messages on a mood scale instantly.
- 💡 **Smart decision-making:** Let an LLM determine the most urgent actions or route issues correctly based on urgency.

#### The Lifecycle of an Event-Driven Automation

1. **The Trigger:** A real-world event that acts as the entrance (e.g., Webhook, New Email, Form Submission). It contains a **payload** of variables.
2. **The Steps:** Sequential actions that consume earlier variables, process them using logical templates or LLM prompts, and append new results to the context.
3. **The Outputs:** Downstream endpoints that export the transformed results (e.g. sending a customized auto-draft email).
`,
    interactiveStep: {
      goal: "Simulate a basic notification pipeline. Update the Action email body to reference the dynamic trigger message using {{trigger.message}} and see how the engine resolves it.",
      defaultSteps: [
        {
          id: "trig-1",
          name: "Webhook Received",
          type: "TRIGGER",
          config: {
            webhookUrl: "https://api.academy.com/v1/webhook/lesson_intro",
          },
        },
        {
          id: "act-1",
          name: "Draft Outbound Email",
          type: "ACTION_EMAIL",
          config: {
            emailTo: "admin@company.com",
            emailSubject: "Inbound notification: {{trigger.sender}}",
            emailBody: "Hello! We received a new message: '{{trigger.message}}'. Let's automate this!",
          },
        },
      ],
      sampleInput: {
        sender: "Jane Doe (Tech Lead)",
        message: "We need urgent help with our database subscription keys.",
        timestamp: "2026-06-01T08:15:00Z",
      },
      expectedSolutionExplanation: "Make sure you use trigger substitution variables inside brackets like {{trigger.message}}.",
    },
  },
  {
    id: "variables-101",
    section: "1. Core Logic",
    title: "Variable Injection & Context Handling",
    contentMarkdown: `### 🧩 Resolving Dynamic Tokens

Workflows cannot be static; they must adapt dynamically to the payload of each individual trigger. To accomplish this, automation engines pass an accumulated **Context Pool** between blocks.

Any outcome generated by previous steps is saved inside this pool and can be referenced by downstream blocks using special brackets.

#### syntax format:
- \`{{trigger.variable_name}}\` to grab fields from the starting webhook or trigger payload.
- \`{{steps.step_id_name.output.variable}}\` to grab results returned by action/AI blocks that ran earlier.

#### Pro Tip on Variables:
- If your trigger contains nested data like \`{ "user": { "profile": { "name": "Alex" } } }\`, you access it by writing \`{{trigger.user.profile.name}}\`.
- Be mindful of exact spelling! If a variable is missing or typed incorrectly, the automation engine will output empty string or throw a variable resolution error.
- Use the **Variables Dropdown** helper in our workspace block to easily insert correctly configured tokens without manual typos.
`,
    interactiveStep: {
      goal: "Experiment with nesting! Try grabbing the account holder's business industry from the payload below in your draft body using the dynamic trigger path.",
      defaultSteps: [
        {
          id: "trig-nested",
          name: "New Lead Form",
          type: "TRIGGER",
          config: {
            webhookUrl: "https://api.academy.com/v1/webhook/leads_nested",
          },
        },
        {
          id: "act-email-nested",
          name: "Send Welcome",
          type: "ACTION_EMAIL",
          config: {
            emailTo: "marketing@company.com",
            emailSubject: "New Industry Lead: {{trigger.account.industry}}",
            emailBody: "Hi sales! We have a lead in the {{trigger.account.industry}} category. Company: {{trigger.account.companyName}}.",
          },
        },
      ],
      sampleInput: {
        account: {
          companyName: "Futuristic Core",
          industry: "Cybersecurity & Cryptography",
        },
        user: { name: "Sarah Connor" },
      },
      expectedSolutionExplanation: "Use {{trigger.account.industry}} and {{trigger.account.companyName}} to resolve nested details correctly.",
    },
  },
  {
    id: "prompt-eng",
    section: "2. Cognitive Block",
    title: "AI & Prompt Engineering inside Workflows",
    contentMarkdown: `### 🧠 Prompting for Background Automations

Prompting inside a user-facing chatbot is very forgiving: if the Chatbot rambles, the user can just ask to clarify or reformat. 

**But inside automated pipelines, rambling is a critical bug.** If an LLM block returns long conversational greetings ("Sure, I can help you with that! Here is the extracted value...") instead of *just* the required data, downstream steps like e-mail senders or databases will log conversational junk.

#### Core Rules of AI Automation prompts:
1. **Never let the LLM talk back to you.** Use system constraints to enforce formatting (e.g., "Output ONLY the drafted reply, without conversational greetings or explanations").
2. **Be highly descriptive about inputs.** Format input text clearly using markers:
   - *Review Content: "{{trigger.message}}"*
3. **Use Few-Shot Examples:** Give the block concrete examples of inputs and ideal outputs. This dramatically reduces hallucination and locks down tone.
`,
    interactiveStep: {
      goal: "Build an AI Prompt action that extracts the core sentiment and a suggested response template. Instruct Gemini to output in a strict structured mode.",
      defaultSteps: [
        {
          id: "trig-review",
          name: "Review Received",
          type: "TRIGGER",
          config: {},
        },
        {
          id: "ai-prompt-1",
          name: "Analyze and Draft Feedback",
          type: "ACTION_AI_PROMPT",
          config: {
            promptTemplate: "You are a customer response assistant.\nAnalyze the review: \"{{trigger.reviewText}}\"\nGenerate a brief, friendly support note thanking them and resolving their problem. Limit to 2 sentences. No conversational meta-intro.",
            responseSchema: "text",
          },
        },
      ],
      sampleInput: {
        reviewer: "David Lightman",
        reviewText: "The system is too slow on desktop, but the mobile version works flawlessly. Took 3 minutes to load.",
      },
      expectedSolutionExplanation: "The AI Prompt step will automatically replace {{trigger.reviewText}} and simulate running the generation on Gemini.",
    },
  },
  {
    id: "filters-routing",
    section: "3. Logical Control",
    title: "Filters, Classifiers & Logical Routing",
    contentMarkdown: `### 🔀 Smart Branching using Rules

If every automation processed every event identically, your systems would trigger millions of unnecessary operations and send spam emails.

**Condition Filters** allow workflows to make choices:
- *Only continue running this workflow if the incoming ticket sentiment is classified as "Urgent" or "billing_dispute".*

#### How Filters Execute:
- A filter checks a dynamically resolved property against an expected static value (e.g., Check if \`{{steps.ai_detector.output.sentiment}}\` equals \`negative\`).
- If the assessment evaluates to **true**, the workflow continues to the next step.
- If the assessment evaluates to **false**, the workflow **halts immediately** with a status of 'filtered' or 'halted'. No downstream servers, databases, or notification webhooks are touched. This saves enormous API overhead and computational limits!
`,
    interactiveStep: {
      goal: "Setup a Filter condition to block execution unless the incoming ticket deal is worth more than $5000.",
      defaultSteps: [
        {
          id: "trig-deal",
          name: "Contract Submitted",
          type: "TRIGGER",
          config: {},
        },
        {
          id: "filter-deal",
          name: "Check Deal Budget",
          type: "ACTION_FILTER",
          config: {
            filterField: "trigger.budget",
            filterOperator: "greater_than",
            filterValue: "5000",
          },
        },
        {
          id: "email-premium",
          name: "Notify VIP Account Exec",
          type: "ACTION_EMAIL",
          config: {
            emailTo: "vip@company.com",
            emailSubject: "🚨 HIGH SECURITY VIP DEAL: {{trigger.company}}",
            emailBody: "A high budget contract was detected: ${{trigger.budget}}. Please contact them ASAP.",
          },
        },
      ],
      sampleInput: {
        company: "Omni Consumer Products",
        budget: "12000",
      },
      expectedSolutionExplanation: "The budget $12,000 exceeds $5,000, so the filter evaluates to success and the downstream actions fire.",
    },
  },
  {
    id: "process-mining",
    section: "4. Process Mining",
    title: "Process Mining & Bottleneck Discovery",
    contentMarkdown: `### 🔍 Process Mining and Bottleneck Spotting

In high-volume enterprises, millions of operational workflow logs are generated daily, but identifying which steps cause critical delays (bottlenecks) used to require manual audit consultants.

**Process Mining** refers to the technique of digesting event logs containing timestamps and task names, parsing the sequential flow, and discovering the absolute "as-is" graph:
- 📊 **Process Discovery:** Building a flow chart automatically based on timestamp event traces rather than user memory.
- ⚡ **Conformance Checking:** Analyzing whether staff actually follow approved procedures or bypass security/policy steps.
- 🚦 **Performance Analysis:** Detecting exactly how many minutes/days a task gets "stuck" between stages (bottlenecks).

#### Processing Event Streams via AI
By feeding unstructured log series into an LLM block inside a workflow step, you can extract cleanly structured JSON details detailing: Name, State, Active Processing Latency, and recommendations to dissolve friction.`,
    interactiveStep: {
      goal: "Simulate a process mining trace parser. Build an AI Prompt node that extracts the state flow, start/end timestamps, and calculates the total process bottleneck duration in minutes from the log feed.",
      defaultSteps: [
        {
          id: "trig-log",
          name: "System Log Dump Trigger",
          type: "TRIGGER",
          config: {},
        },
        {
          id: "ai-miner",
          name: "Extract Trace Bottlenecks",
          type: "ACTION_AI_PROMPT",
          config: {
            promptTemplate: "Extract event trace details from: \"{{trigger.log_content}}\". Output a JSON representation with keys 'processName', 'durationMinutes' (difference between finish and start), and 'identifiedBottleneck' (the step with the biggest delay or brief reason).",
            responseSchema: "json",
          },
        },
      ],
      sampleInput: {
        log_content: "UserId: 782 | Process: OUTBOUND_DISPATCH | Trace: [STAGE1: READY_FOR_PACK] at 09:00:00Z -> [STAGE2: PACKING_COMPLETED] at 09:12:00Z -> [STAGE3: SHIPPING_PICKUP_DELAY] at 09:58:00Z",
      },
      expectedSolutionExplanation: "The instruction should extract the events, calculate the elapsed duration (58 minutes total), and flag 'SHIPPING_PICKUP_DELAY' as the bottleneck bottleneck.",
    },
  },
  {
    id: "rpa-basics",
    section: "5. RPA Integration",
    title: "Robotic Process Automation (RPA) Basics",
    contentMarkdown: `### 🤖 UI Clicks vs. Direct APIs: RPA Foundations

In the absolute ideal world, every piece of software has a lightning-fast API. But in the real world of banking, health insurance, and governments, workflows frequently touch **legacy mainframes or desktop apps** that have zero programmatic endpoints.

**Robotic Process Automation (RPA)** solves this by creating software robots that mimic human browser and screen activities:
- 🖱️ Clicking buttons, dragging elements, and typing text into input fields automatically.
- 📋 Copying data from desktop applications, PDFs, or files and pasting them into modern Cloud endpoints.

#### RPA vs. Modern API Integrations
- **API First:** If a direct endpoint is available, use standard API/Webhook blocks. It is faster, robust, and doesn't break when a button gets moved on a screen.
- **RPA as Last Resort:** Use RPA when automating archaic legacy portals, thick client software, or web forms that lack credentials or integrations.

#### Building RPA Bridges
You can bridge modern AI/API pipelines to RPA systems using Outbound Webhooks. When an event triggers, dispatch a POST hook to kick off local RPA agents (e.g. UiPath, BluePrism, Playwright macros) to form-fill on Windows desktops.`,
    interactiveStep: {
      goal: "Simulate legacy system RPA bridging. Setup an outbound Webhook action formatted with legacy CRM coordinates to trigger a desktop robotic screen macro.",
      defaultSteps: [
        {
          id: "trig-legacy-event",
          name: "Legacy Event Received",
          type: "TRIGGER",
          config: {},
        },
        {
          id: "webhook-rpa-bridge",
          name: "UIPath Dispatcher",
          type: "ACTION_WEBHOOK",
          config: {
            webhookUrl: "https://orchestrator.agency.io/v2/jobs/start?robot=ui_filler_bot",
          },
        },
      ],
      sampleInput: {
        customerName: "Bruce Wayne",
        recordId: "9005-A",
        legacyFormTarget: "Windows_ledger_form_32",
      },
      expectedSolutionExplanation: "Ensures legacy-form metadata triggers an outbound webhook dispatch to spark macro-driven screen activity.",
    },
  },
  {
    id: "resilient-workflow",
    section: "6. Resilient Workflows",
    title: "Enterprise Workflow Resilience",
    contentMarkdown: `### 🛡️ Building Fault-Tolerant, Bulletproof Systems

When deploying automations that control business-critical infrastructure, **failures will happen**. Relied-upon APIs will rate-limit, servers will time out, or webhook hosts will return DNS failures.

If workflows are built with simple, fragile chains, a single transient network error can halt millions in transactions or leave customers stranded.

#### Pillars of Workflow Resilience
1. **Idempotence:** Design steps so that running them multiple times with the exact same payload doesn't cause duplicate billing or double emailing.
2. **Exponential Backoff:** Implementing automatic retries on API calls with increasing wait intervals (1s, 2s, 4s, 8s) to give down servers breathing room.
3. **Dead Letter Queues (DLQ) & Error Handling:** When a critical action fails repeatedly, halt cleanly and dispatch dynamic alerts to support logs rather than crashing silent in the dark.

In a logical pipeline, we can use filtering logic to check for FAILED state variables and send urgent error alerts immediately.`,
    interactiveStep: {
      goal: "Build an error resilience fallback branch. Connect a filter that checks if the trigger webhook status is 'FAILED', and if so, sends an email notification.",
      defaultSteps: [
        {
          id: "trig-error",
          name: "API Monitor Hook",
          type: "TRIGGER",
          config: {},
        },
        {
          id: "filter-error",
          name: "Detect API Malfunction",
          type: "ACTION_FILTER",
          config: {
            filterField: "trigger.status",
            filterOperator: "equals",
            filterValue: "FAILED",
          },
        },
        {
          id: "email-admin-alert",
          name: "Notify DevOps Team",
          type: "ACTION_EMAIL",
          config: {
            emailTo: "devops@corporation.com",
            emailSubject: "⚠️ CRITICAL SYSTEM FAILURE: {{trigger.service}}",
            emailBody: "Attention support team: The service '{{trigger.service}}' failed with error: '{{trigger.errorMessage}}'. Action required.",
          },
        },
      ],
      sampleInput: {
        service: "Stripe Payment Gateway Bridge",
        status: "FAILED",
        errorCode: "ERR_TIMEOUT_504",
        errorMessage: "Stripe servers failed to respond within 30000ms limit.",
      },
      expectedSolutionExplanation: "Checks if the resolved status equals 'FAILED' to ensure only system breakdowns trigger high-alert emails.",
    },
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: "sentiment_reply",
    title: "Customer Sentiment Dispatcher",
    difficulty: "Beginner",
    description: "Build an automated ticket triage that parses feedback sentiment, draft polite replies for negative notes, and skips happy alerts to avoid desk clutter.",
    instructions: `### Objective:
Given an incoming customer ticket:
1. Create an **AI Prompt** or **AI Classification** step to analyze the ticket text.
2. If sentiment is **negative**: Draft a professional customer recovery reply using the prompt step, and simulate adding it to a step.
3. Configure a **Filter step** to only continue email drafts for negative cases, keeping your inbox free of positive clutter.

### Expected variables to reference:
- Email body should reference: \`{{steps.your_ai_step_id.output.response}}\` or \`{{trigger.message}}\` appropriately.`,
    requiredSteps: ["TRIGGER", "ACTION_AI_PROMPT", "ACTION_FILTER"],
    testInputs: [
      {
        label: "Case A: Fuming Customer",
        data: {
          customerName: "Alex Vance",
          message: "I paid for the pro tier subscription but my account is still locked to starter features! This is unacceptable, I have a big demo in an hour. Please refund or fix this now!",
        },
      },
      {
        label: "Case B: Thrilled Customer",
        data: {
          customerName: "Gordon Freeman",
          message: "Best service ever. The layout is beautiful and extremely fast! Highly recommended.",
        },
      },
    ],
    successCondition: "Successfully evaluates filters and generates polished responses for complaints, while filtering positive ones.",
  },
  {
    id: "lead_enricher",
    title: "Enterprise Deal Detector & Enrichment",
    difficulty: "Intermediate",
    description: "Scan prospective inbound query requests, extract deal sizing, filter out entries under $2,000 budget, and auto-compose bespoke pitching notes.",
    instructions: `### Objective:
1. Parse the inbound lead mail using an **AI Action** and extract: **companyName**, **estimatedBudget**, and **painPoint**.
2. Run a **Filter** to stop workflows with a budget under \`2000\` dollars.
3. If it passes, compose a personalized high-priority Slack/Email alert highlighting the extracted company details and custom sales recommendations.

### Variables format:
- Create an AI Step.
- Reference extracted factors: \`{{steps.enricher.output.companyName}}\`, \`{{steps.enricher.output.estimatedBudget}}\`.`,
    requiredSteps: ["TRIGGER", "ACTION_AI_PROMPT", "ACTION_FILTER", "ACTION_EMAIL"],
    testInputs: [
      {
        label: "Case A: Small business lead",
        data: {
          leadEmail: "bob@localshop.com",
          message: "Hi, I run a local bakery and want a simple 1-page menu card. Our absolute max budget is $450. Can you help?",
        },
      },
      {
        label: "Case B: Fortune 500 buyer",
        data: {
          leadEmail: "vp_digital@acmeglobal.com",
          message: "Hello, We are looking to migrate our supply logistics tracker for 45 warehouses. We have scoped out about $18,000 for this project Phase 1 and expect to launch next month.",
        },
      },
    ],
    successCondition: "Budget criteria filters out Bob's bakery budget, but successfully executes and enrichment drafts for VP ACME.",
  },
  {
    id: "auto_categorizer",
    title: "Support Auto-Categorizer & Router",
    difficulty: "Advanced",
    description: "Build an automated classifier that parses technical problems versus billing concerns, routes to proper agent, and escalates critical system issues.",
    instructions: `### Objective:
1. Take incoming logs and use a **Classification AI block** or prompt to tag them into: \`Billing\`, \`Technical Help\`, or \`Security Incident\`.
2. Map outcomes to conditional paths or create high-urgency alerts if Billing or Security is detected.
3. Test with both an authentication error complaint and standard billing card update problems.`,
    requiredSteps: ["TRIGGER", "ACTION_AI_PROMPT", "ACTION_FILTER"],
    testInputs: [
      {
        label: "Case A: Security Hazard",
        data: {
          userEmail: "hacker_scout@sandbox.io",
          message: "⚠️ SECURITY WARNING: I discovered a public endpoint leaking user profile emails on /api/profiles/test. Fix this immediately as standard users can dump database rows.",
        },
      },
      {
        label: "Case B: Standard Invoice query",
        data: {
          userEmail: "billing_mgr@retail.com",
          message: "Can we get our invoice updated to list our VAT number: EU987654321? Thank you.",
        },
      },
    ],
    successCondition: "Successfully tags categories and correctly escalates high security incident payload.",
  },
];
